name: example-environment
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - pip
  - r-base
  - r-tidyverse
  - r-dplyr
  - r-ggpubr
  - pip:
    - nbgitpuller
    - sphinx-gallery
    - pandas
    - matplotlib
